# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QuPaiTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AliyunVideoSDKStd', '3.16.0'
#pod 'QuCore-ThirdParty', '3.15.0'
#pod 'AlivcConan', '1.0.3'
pod 'VODUpload'
pod 'AliyunOSSiOS'
pod 'AliPlayerSDK_iOS'


end
